### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by aarjae** [ardalanamini/node-kutt#3]
Will this package work in a browser?
Or just Node

**Comment by ardalanamini** [comment]
It works in browsers!
It’s browser support is completely dependent in ‘axios’ package

**Comment by abhijithvijayan** [comment]
> It works in browsers!
> It’s browser support is completely dependent in ‘axios’ package

@ardalanamini 
So, no separate `axios` package is needed for while calling right!

@aarjae implemented use of this package in the browser extension for kutt ([kutt-extension](https://github.com/abhijithvijayan/kutt-extension)) in commit https://github.com/abhijithvijayan/kutt-extension/commit/edba29be6c85d29a22abacc86c951ac2e0cf2f11

I hope you'll keep this repo updated for the time being. 

Thanks 👍
