### ISSUE TITLE
Unexpect Dependencie: Cannot find module 'axios'

### ISSUE THREAD

**Issue by machao7** [ardalanamini/node-kutt#69]
i think http/https module will be a better choice for node env. 
In my node project, axios is not a dependency. When I install kutt, I got the error which in the title.

**Comment by ardalanamini** [comment]
@machao7 Thanks for the enhancement request.
Currently `axios` is a `peer-dependency`, after reading this issue, initially, I was thinking about using `fetch` instead, but its support in `Node.js` is only added in the latest versions and not backward compatible, so the only relatively clean solution I can think of at the moment is using the `package.json` `imports`  using HTTP(S) module in node and `fetch` in other environments to completely remove the need for any dependencies, what do you think about this solution? 🤔
