### ISSUE TITLE
bug: Generic error makes it hard to debug

### ISSUE THREAD

**Issue by snimesh17** [ardalanamini/node-kutt#95]
no matter what type of operation I try to do using node-kutt, I always get the same generic error, which makes it really hard to debug.

For example if I'm not passing "domain" in links.create function I get the same network error.
If something else is wrong still i get the same network error that makes it hard to debug the exact problem.

STEPS to replicate this issue:
one way would be to try creating the same existing domain again.
other way would be to simply not pass "domain" in links.create function.

The error I get every single time is:
```
Error: Network response was not OK
at ClientRequest.<anonymous> (/app/node_modules/kutt/src/api/API.node.ts:68:20)

**Comment by ardalanamini** [comment]
@snimesh17 sorry for the late reply, this issue should be fixed with the new release.

The new error message will use the `kutt` response data and only default to a generic message.

Additionally, the response `status` and `data` are attached as the `cause` of the error.
